### ISSUE TITLE
Backend Functionality to IndexingService

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/indexing-service#3]
#### Description

Indexing Service needs to be able to process the following request via a REST API or Messaging service:
```json
"payload": {
        "indexingServiceInput": {
          "activity": "replace",
          "targetIndex": "test-index",
          "useBulk": true,
          "sourceData":
          [
            {
              "docType": "test",
              "inputType": "URI/Data",            
              "input": "file:///file-coming-from-framing"
            }
          ]
        }
    } 
```

Questions to be answered:
* is a response to the request expected - implementing RPC style of communication
* async processing of document - needed for the bulk and in order to be non-blocking
* when to add [rollover ](http://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.client.IndicesClient.rollover)and when to add [refresh ](http://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.client.IndicesClient.refresh)
* manage aliases, default index and default doc_type (random generation or expected)
* `docType` required when usebulk=false

#### DoD
Implemented functionality

#### Testing
Unit Testing

**Comment by blankdots** [comment]
`targetIndex` - changed to `targetAlias` - to reflect that the indexes are generated and we operate on aliases.
**Rollover** provides different functionality than the one initially envisioned, the solution would be to remove an alias from an old index and add it to the new index.

There are multiple ways to perform different activities on a document, it is up to the service design how much of the client interface we want to abstract.
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html
https://www.elastic.co/guide/en/elasticsearch/guide/current/partial-updates.html

**Comment by blankdots** [comment]
Minimal configuration:
```yml
version: '2'
services:
  messagebroker:
    image: rabbitmq:3.6.12-management
    ports:
      - '4369:4369'
      - '5671:5671'
      - '5672:5672'
      - '15671:15671'
      - '15672:15672'
      - '25672:25672'
    environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=password
  fuseki:
    image: attxproject/attx-fuseki:fuseki3.4.0
    environment:
      - ADMIN_PASSWORD=pw123
    ports:
      - 3030:3030
  es5:
    image: attxproject/attx-es5:1.0
    # volumes:
    #   - ./attx-data/elasticsearch5:/usr/share/elasticsearch/data
    ports:
      - 9210:9210
      - 9310:9310
  provservice:
    image: attx-dev:5000/provenance-service:latest
    depends_on:
        - messagebroker
        - fuseki
    environment:
        - MHOST=messagebroker
        - GHOST=fuseki
    ports:
      - 7030:7030
    links:
      - messagebroker:messagebroker

  indexservice:
    image: attx-dev:5000/index-service:latest
    depends_on:
        - messagebroker
    environment:
        - MHOST=messagebroker
        - ESHOST=es5
    ports:
      - 4304:4304
    links:
      - messagebroker:messagebroker
```
